name: Job Fetcher

on:
  workflow_dispatch:
    inputs:
      country:
        description: 'Country for job search (e.g., United States)'
        required: true
      keyword:
        description: 'Optional keyword for job search (e.g., software engineer)'
        required: false
        default: ''
      wp_site_url:
        description: 'WordPress site URL (e.g., https://example.com)'
        required: true

jobs:
  fetch-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 urllib3

      - name: Verify FETCHER_TOKEN
        run: |
          if [ -z "$FETCHER_TOKEN" ] || ! echo "$FETCHER_TOKEN" | grep -q "^github_pat_"; then
            echo "Error: FETCHER_TOKEN is missing or does not start with 'github_pat_'. Please set a valid GitHub Personal Access Token in GitHub secrets."
            exit 1
          else
            echo "FETCHER_TOKEN is set and valid."
          fi
        env:
          FETCHER_TOKEN: ${{ secrets.FETCHER_TOKEN }}

      - name: Run fetcher
        env:
          WP_SITE_URL: ${{ github.event.inputs.wp_site_url }}
          WP_USERNAME: ${{ secrets.WP_USERNAME }}
          WP_APP_PASSWORD: ${{ secrets.WP_APP_PASSWORD }}
          COUNTRY: ${{ github.event.inputs.country }}
          KEYWORD: ${{ github.event.inputs.keyword }}
          FETCHER_TOKEN: ${{ secrets.FETCHER_TOKEN }}
        run: python fetcher.py
