name: Job Scraper

on:
  schedule:
    - cron: '0 8 * * *'  # Runs every day at 8:00 UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 lxml

      - name: Run scraper
        run: python scraper.py  # Replace with your script filename if different
