name: Job Scraper

on:
  workflow_dispatch:   # allow manual trigger
  schedule:
    - cron: "0 * * * *"   # runs every hour (you can adjust/remove if you want looping only)

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: |
          echo "🚀 Starting job scraper..."
          python scraper.py || exit 1
          echo "✅ Scraper finished, waiting 5 minutes..."
          sleep 300  # wait 5 minutes
          echo "🔄 Restarting workflow..."
          gh workflow run scraper.yml
        env:
          WP_USER: ${{ secrets.WP_USER }}
          WP_PASS: ${{ secrets.WP_PASS }}
          WP_URL:  ${{ secrets.WP_URL }}

      - name: Done
        run: echo "Scraper loop complete."
