name: Run LinkedIn Scraper
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
    inputs:
      country:
        description: 'Country to scrape jobs for'
        required: true
        default: 'Mauritius'
      specialty:
        description: 'Job specialty or keywords'
        required: false
        default: ''
jobs:
  scrape:
    runs-on: ubuntu-latest
    env:
      WP_USERNAME: ${{ secrets.WP_USERNAME }}
      WP_APP_PASSWORD: ${{ secrets.WP_APP_PASSWORD }}
      COUNTRY: ${{ github.event.inputs.country || 'Mauritius' }}
      SPECIALTY: ${{ github.event.inputs.specialty || '' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Log inputs
        run: |
          echo "Running scraper with COUNTRY=$COUNTRY, SPECIALTY=$SPECIALTY"
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run scraper
        run: python scraper.py > scraper.log 2>&1
      - name: Upload scraper log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: scraper-log
          path: scraper.log
      - name: Commit changes
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Actions"
          git add mauritius_processed_job_ids.csv last_processed_page.txt scraped_jobs.json || true
          git status
          git commit -m "Update processed files and scraped_jobs.json after scrape" || echo "No changes to commit"
          git push || echo "No changes to push"
