# Configuration for the job scraper
scraper:
  wordpress:
    url: "https://mauritius.mimusjobs.com/wp-json/wp/v2/"
    endpoints:
      job_listings: "job-listings"
      company: "company"
      media: "media"
      job_type: "job_listing_type"
      job_region: "job_listing_region"
    username: "mary"
    app_password: "Piab Mwog pfiq pdfK BOGH hDEy"
  files:
    processed_ids: "mauritius_processed_job_ids.csv"
    last_page: "last_processed_page.txt"
    scraped_jobs: "scraped_jobs.json"
  scraping:
    base_url: "https://www.linkedin.com/jobs/search"
    location: "Mauritius"
    headers:
      user-agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36"
    max_pages: 15
    delay:
      min: 5
      max: 10
    retries:
      total: 3
      backoff_factor: 1
      status_forcelist: [429, 500, 502, 503, 504]
    timeout: 15
