name: Scraper Workflow

on:
  workflow_dispatch:
    inputs:
      wp_username:
        description: 'WordPress username for REST API authentication'
        required: true
      wp_app_password:
        description: 'WordPress application password for REST API authentication'
        required: true
      scrape_location:
        description: 'Location for job scraping (e.g., Worldwide, New York)'
        required: true

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 urllib3

      - name: Run scraper
        env:
          WP_BASE_URL: ${{ secrets.WP_BASE_URL }}
          WP_USERNAME: ${{ github.event.inputs.wp_username }}
          WP_APP_PASSWORD: ${{ github.event.inputs.wp_app_password }}
          SCRAPE_LOCATION: ${{ github.event.inputs.scrape_location }}
        run: python scraper.py

