name: Run LinkedIn Scraper

on:
  schedule:
    - cron: '0 * * * *'  # Every hour at minute 0
  workflow_dispatch:  # Manual trigger with inputs
    inputs:
      country:
        description: 'Country to scrape'
        required: true
        default: 'Mauritius'
      specialty:
        description: 'Job specialty/keywords'
        required: false
        default: ''

jobs:
  scrape:
    runs-on: ubuntu-latest
    env:
      WP_USERNAME: ${{ secrets.WP_USERNAME }}
      WP_APP_PASSWORD: ${{ secrets.WP_APP_PASSWORD }}
      GH_PAT: ${{ secrets.GH_PAT }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: python script.py --country "${{ inputs.country }}" --specialty "${{ inputs.specialty }}"

      - name: Commit changes
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Actions"
          git add mauritius_processed_job_ids.csv last_processed_page.txt || true
          git commit -m "Update processed files after scrape" || echo "No changes to commit"
          git push || echo "No changes to push"
